version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=production
    volumes:
      - ./server:/usr/src/app
    networks:
      - badbank-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./client:/usr/src/app
    networks:
      - badbank-network

networks:
  badbank-network:
    driver: bridge
